### ISSUE TITLE
correction on documentation: git clone command

### ISSUE THREAD

**Issue by scientific-method-course** [Travelbacon/MMM-NLDepartureTimes#9]
I think the install command should be 
`git clone https://github.com/Travelbacon/MMM-NLDepartureTimes`

The command given in de Readme file only works for the author I think.

**Comment by Travelbacon** [comment]
> I think the install command should be `git clone https://github.com/Travelbacon/MMM-NLDepartureTimes`
> 
> The command given in de Readme file only works for the author I think.
Thank you for pointing this out. This command only works when SSH is installed. I changed with the HTTP version you wrote.

**Comment by Travelbacon** [comment]
Solved in the new Readme.md.
